name: Label PRs

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
